[package]
name = "sedenion-rule-creator"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.6"
pest_derive = "2.6"
lazy_static = "1.4.0"
thiserror = "1.0.44"
anyhow = "1.0.72"
